version: "3.9"

services:
  app:
    build: .
    container_name: finance_app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: finance_db
      DB_USER: finance
      DB_PASS: financepass
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: finance_db
    environment:
      MYSQL_DATABASE: finance_db
      MYSQL_USER: finance
      MYSQL_PASSWORD: financepass
      MYSQL_ROOT_PASSWORD: rootpass
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro

volumes:
  dbdata:
